### ISSUE TITLE
Error when decimating with animation weighting

### ISSUE THREAD

**Issue by xantoz** [absolute-quantum/cats-blender-plugin#249]
Got this error when trying to decimate a model and enabling "Animation Weighting"

```
Python: Traceback (most recent call last):
  File "C:\Users\[REDACTED]\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\cats-blender-plugin-master\tools\decimation.py", line 182, in execute
    self.decimate(context)
  File "C:\Users\[REDACTED]\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\cats-blender-plugin-master\tools\decimation.py", line 264, in decimate
    for key_block in mesh.data.shape_keys.key_blocks[1:]:
AttributeError: 'NoneType' object has no attribute 'key_blocks'

location: <unknown location>:-1
```

of note might be that some of the meshes lack even a "Basis" shape key, it would seem...

**Comment by xantoz** [comment]
Confirmed adding a "Basis" shape key to those meshes made it not error.

**Comment by feilen** [comment]
That's a known issue, fixed in development version
