### ISSUE TITLE
Install Development Version option broken.

### ISSUE THREAD

**Issue by ghost** [absolute-quantum/cats-blender-plugin#426]
Whenever I click the button to do it, an error is brought up.

Python: Traceback (most recent call last):
  File "C:\Users\AMD Gamer\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\updater.py", line 122, in execute
    bpy.ops.cats_updater.confirm_update_panel('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\AMD Gamer\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\updater.py", line 219, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 4.1)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float

location: C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\bpy\ops.py:130

location: <unknown location>:-1

**Comment by Munsterlandr** [comment]
Seems like a broader issue with the newer version of python used in 3.0. I've found switching to Blender 2.80 solves the issue, but also using a pre-existing model made in 3.1.2 gets rid of all Vertex Groups.

**Comment by ghost** [comment]
Thanks. Using older versions of Blender and stuff fixed the issue.
