### ISSUE TITLE
Fixing materials and most fixes breaking skeleton

### ISSUE THREAD

**Issue by chilletize** [absolute-quantum/cats-blender-plugin#439]
Skeleton disconnects from the mesh rendering it useless, it throws this error too:

Python: Traceback (most recent call last):
  File "C:\Users\nikyv\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-0-19-0\tools\armature.py", line 1010, in execute
    Common.fix_twist_bones(mesh, bones_to_delete)
  File "C:\Users\nikyv\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-0-19-0\tools\common.py", line 2150, in fix_twist_bones
    mix_weights(mesh, vg_twist.name, vg_twist.name, mix_strength=0.2, mix_mode='SUB', delete_old_vg=False)
  File "C:\Users\nikyv\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-0-19-0\tools\common.py", line 1789, in mix_weights
    apply_modifier(mod)
  File "C:\Users\nikyv\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-0-19-0\tools\common.py", line 316, in apply_modifier
    bpy.ops.object.modifier_apply(modifier=mod.name)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Modifier is disabled, skipping apply

location: <unknown location>:-1

Doing another fix (Combining meshes) does the same thing disconnecting the skeleton from the mesh and throwing this error instead:

Python: Traceback (most recent call last):
  File "C:\Users\nikyv\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-0-19-0\tools\armature.py", line 1010, in execute
    Common.fix_twist_bones(mesh, bones_to_delete)
  File "C:\Users\nikyv\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-0-19-0\tools\common.py", line 2150, in fix_twist_bones
    mix_weights(mesh, vg_twist.name, vg_twist.name, mix_strength=0.2, mix_mode='SUB', delete_old_vg=False)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 2: invalid start byte

location: <unknown location>:-1

**Comment by feilen** [comment]
The error is probably the reason for the disconnect. Would you mind trying again a couple of times? Apparently this issue is intermittant.

**Comment by Mysteryem** [comment]
This is a duplicate of https://github.com/absolute-quantum/cats-blender-plugin/issues/396
