### ISSUE TITLE
Atlas Error

### ISSUE THREAD

**Issue by strawbnyeko** [absolute-quantum/cats-blender-plugin#454]
Im having an issue to where I can't export my model because of an issue in the code.

Traceback (most recent call last):
File "C:\Users\senne\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\material-combiner-addon-master\operators\combiner\combiner.py", line 29, in execute
atlas = get_atlas(scn, self.structure, size)
File "C:\Users\senne\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\material-combiner-addon-master\operators\combiner\combiner_ops.py", line 192, in get_atlas
img.paste(get_gfx(scn, mat, i, i['gfx']['img']), (i['gfx']['fit']['x'] + int(scn.smc_gaps / 2),
File "C:\Users\senne\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\material-combiner-addon-master\operators\combiner\combiner_ops.py", line 156, in get_gfx
img = Image.open(src).convert('RGBA')
File "C:\Users\senne\AppData\Roaming\Python\Python37\site-packages\PIL\Image.py", line 2944, in open
"cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'C:\Users\senne\3D Objects\Ears&Tail\tex\body2.png'

location: :-1

**Comment by LoveRenamon** [comment]
are you messing with [material-combiner-addon](https://github.com/Grim-es/material-combiner-addon), its not a cats issue.
For some reason you've two addons that create atlas
