### ISSUE TITLE
getting error with new update for blender

### ISSUE THREAD

**Issue by CraftingKahuka** [absolute-quantum/cats-blender-plugin#458]
can't export model or update the plugin

error message:

Python: Traceback (most recent call last): 
File "C:\Users\(my name)\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 880, in execute bpy.ops.cats_importer.display_error('INVOKE DEFAULT')
File "D:\Program Files (x86)\3.1\scripts\modules\bpy\ops.py", line 130, in_call_ret=_op_call(self.idname_py(), C_dict, kw, C_exec, C_undo
RuntimeError: Error: Python: Traceback (most recent call last): 
   File "C:\Users]\(my name)\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 966, in invoke return context window_manager.invoke_props_dialog(self, width=dpi_value*6.1)
   TypeError: WindowManager.invoke_props_dialog():error with keyboard argument "width" - Function.width expected an int type, not float
   location D:\Program Files(x86)\3.1\scripts\modules\bpy\ops.py:130
   location: <unknown location>:-1

**Comment by Nogha12** [comment]
![image](https://user-images.githubusercontent.com/77655502/167914375-08d38ed0-82aa-4e5b-a2f9-c8aa91745c2f.png)
I get the same error. For example, when trying to open the "Fix Model" settings.

**Comment by feilen** [comment]
#379

**Comment by docrenhao** [comment]
same

**Comment by Eevieian** [comment]
I am also getting this error anyone know the fix?

**Comment by siskanuri** [comment]
<img width="676" alt="Screenshot 2023-05-12 200816" src="https://github.com/absolute-quantum/cats-blender-plugin/assets/89716827/43e5b9fb-5cf1-4d76-b2ae-bf0af436f386">
how to fix this?
