### ISSUE TITLE
BakeSettings object has no attribute use_pass_ambient_occlusion

### ISSUE THREAD

**Issue by amymelody** [absolute-quantum/cats-blender-plugin#498]
I'm getting this error when baking, using Blender 3.1.2

```
Python: Traceback (most recent call last):
  File "C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\tools\bake.py", line 384, in execute
    self.perform_bake(context)
  File "C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\tools\bake.py", line 622, in perform_bake
    self.bake_pass(context, "diffuse", "DIFFUSE", {"COLOR"}, [obj for obj in collection.all_objects if obj.type == "MESH"],
  File "C:\Users\Amy\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cats-blender-plugin-0-19-0\tools\bake.py", line 294, in bake_pass
    context.scene.render.bake.use_pass_ambient_occlusion = "AO" in bake_pass_filter
AttributeError: 'BakeSettings' object has no attribute 'use_pass_ambient_occlusion'

location: <unknown location>:-1
```

**Comment by feilen** [comment]
Upgrade to the Dev version, or use blender 2.93. We're still working on the new release I'm afraid
