### ISSUE TITLE
fix Model issue

### ISSUE THREAD

**Issue by Nostalgicd** [absolute-quantum/cats-blender-plugin#531]
Python: Traceback (most recent call last):
  File "/Users/j/Library/Application Support/Blender/3.2/scripts/addons/cats-blender-plugin-0-19-0/tools/armature.py", line 1222, in execute
    bpy.ops.mmd_tools.set_shadeless_glsl_shading()
  File "/Applications/Blender.app/Contents/Resources/3.2/scripts/modules/bpy/ops.py", line 115, in __call__
    ret = _op_call(self.idname_py(), None, kw)
AttributeError: Calling operator "bpy.ops.mmd_tools.set_shadeless_glsl_shading" error, could not be found

**Comment by LuWards** [comment]
I have the same problem, unfortunatelly :(

**Comment by The-Beebz** [comment]
Make sure you're not on the workbench render engine and the armature is within a collection inside the scene collection. I found whenever this happened doing this helped. Hope this works for you.
