### ISSUE TITLE
Import Model Error

### ISSUE THREAD

**Issue by mrrobot178912** [absolute-quantum/cats-blender-plugin#538]
bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 1 object(s)
Python: Traceback (most recent call last):
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 540, in execute
    bpy.ops.import_scene.vrm('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
AttributeError: Calling operator "bpy.ops.import_scene.vrm" error, could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 542, in execute
    bpy.ops.cats_importer.install_vrm('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 540, in execute
    bpy.ops.import_scene.vrm('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
AttributeError: Calling operator "bpy.ops.import_scene.vrm" error, could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 632, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 4.5)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float
Location: C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py:113
Python: Traceback (most recent call last):
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\updater.py", line 85, in execute
    bpy.ops.cats_updater.confirm_update_panel('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\updater.py", line 218, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 4.1)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float
Location: C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\ops.py:113
bpy.context.space_data.system_bookmarks_active = 3
Modules Installed (cats-blender-plugin-master) from 'C:\\Users\\User 7\\Downloads\\cats-blender-plugin-master.zip' into 'C:\\Users\\User 7\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 314, in enable
    importlib.reload(mod)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\__init__.py", line 73, in <module>
    importlib.reload(mmd_tools_local)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\__init__.py", line 41, in <module>
    importlib.reload(properties)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\properties\__init__.py", line 8, in <module>
    importlib.reload(morph)
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\properties\morph.py", line 79, in <module>
    class _MorphBase:
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\__init__.py", line 22, in register_wrap
    bl_props = {k:v for k, v in cls.__dict__.items() if isinstance(v, __bpy_property)}
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\__init__.py", line 22, in <dictcomp>
    bl_props = {k:v for k, v in cls.__dict__.items() if isinstance(v, __bpy_property)}
NameError: name '__bpy_property' is not defined

bpy.context.space_data.system_bookmarks_active = 1
Python: Traceback (most recent call last):
  File "C:\Users\User 7\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 98, in execute
    for f in self.files:
TypeError: '_PropertyDeferred' object is not iterable
bpy.ops.cats_importer.import_any_model(filepath="C:\\Users\\User 7\\Desktop\\3d model_.vrm")

**Comment by Darky76** [comment]
you need to download the VRM addon first https://github.com/saturday06/VRM_Addon_for_Blender
