### ISSUE TITLE
Fix Model Python Issue

### ISSUE THREAD

**Issue by Damlius** [absolute-quantum/cats-blender-plugin#541]
Python: Traceback (most recent call last):
  File "C:\Users\damli\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\panels\prop_object.py", line 132, in draw
    c.prop(obj.mmd_joint, 'name_j')
AttributeError: 'Object' object has no attribute 'mmd_joint'

**Comment by rsyyy** [comment]
having the same issue- saw somewhere to try installing Development Version but it gave me the same error when I tryed to do that to-

**Comment by Krislyz** [comment]
> Python: Traceback (most recent call last): File "C:\Users\damli\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\cats-blender-plugin-master\extern_tools\mmd_tools_local\panels\prop_object.py", line 132, in draw c.prop(obj.mmd_joint, 'name_j') AttributeError: 'Object' object has no attribute 'mmd_joint'

Are you using Blender 2.93 LTS?
