### ISSUE TITLE
Bake error, use_pass_ambient_occlusion

### ISSUE THREAD

**Issue by Royalty715** [absolute-quantum/cats-blender-plugin#542]
I have an error when I use the bake - 

Python: Traceback (most recent call last):
  File "C:\Users\royal\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 384, in execute
    self.perform_bake(context)
  File "C:\Users\royal\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 622, in perform_bake
    self.bake_pass(context, "diffuse", "DIFFUSE", {"COLOR"}, [obj for obj in collection.all_objects if obj.type == "MESH"],
  File "C:\Users\royal\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\cats-blender-plugin-master\tools\bake.py", line 294, in bake_pass
    context.scene.render.bake.use_pass_ambient_occlusion = "AO" in bake_pass_filter
AttributeError: 'BakeSettings' object has no attribute 'use_pass_ambient_occlusion'

**Comment by bhoffman67** [comment]
Me as well.  My Process below:

Added a pair of briefs (underware) to a G8M and some hair. 
Utilized the BridgetoBlender for the character.
Opened Blender 3.0.1 and imported said character using bridge and applied the morphs I wanted.
Opened CATS v0.19 and filled in appropriate fields for eye tracking and visemes
Clicked Copy and Bake.

**Comment by feilen** [comment]
This has been fixed in the development version, it should go away if you update

**Comment by bhoffman67** [comment]
no updates where shown as available.  What version should we be running?

**Comment by feilen** [comment]
Try this: https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip
