### ISSUE TITLE
A Wrong is about Fix Model！

### ISSUE THREAD

**Issue by jamyido** [absolute-quantum/cats-blender-plugin#553]
Traceback (most recent call last):
  File "C:\Users\28128\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 445, in execute
    Translate.update_dictionary(to_translate)
  File "C:\Users\28128\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\translate.py", line 438, in update_dictionary
    translations = [translator.translate(text, lang_src='ja', lang_tgt='en').strip() for text in google_input]
  File "C:\Users\28128\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\translate.py", line 438, in <listcomp>
    translations = [translator.translate(text, lang_src='ja', lang_tgt='en').strip() for text in google_input]
  File "C:\Users\28128\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\google_trans_new\google_trans_new.py", line 205, in translate
    raise google_new_transError(tts=self, response=r)
cats-blender-plugin-master.extern_tools.google_trans_new.google_trans_new.google_new_transError: 500 (Internal Server Error) from TTS API. Probable cause: Uptream API error. Try again later.

location: <unknown location>:-1

**Comment by jamyido** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\28128\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\google_trans_new\google_trans_new.py", line 200, in translate
    r.raise_for_status()
  File "D:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://translate.google.com/_/TranslateWebserverUi/data/batchexecute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\28128\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 445, in execute
    Translate.update_dictionary(to_translate)
  File "C:\Users\28128\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\translate.py", line 438, in update_dictionary
    translations = [translator.translate(text, lang_src='ja', lang_tgt='en').strip() for text in google_input]
  File "C:\Users\28128\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\tools\translate.py", line 438, in <listcomp>
    translations = [translator.translate(text, lang_src='ja', lang_tgt='en').strip() for text in google_input]
  File "C:\Users\28128\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\cats-blender-plugin-master\extern_tools\google_trans_new\google_trans_new.py", line 205, in translate
    raise google_new_transError(tts=self, response=r)
cats-blender-plugin-master.extern_tools.google_trans_new.google_trans_new.google_new_transError: 500 (Internal Server Error) from TTS API. Probable cause: Uptream API error. Try again later.

location: <unknown location>:-1

**Comment by jamyido** [comment]
I can't fix this api by myself

**Comment by Krislyz** [comment]
Are you using Blender 2.93 LTS?
