### ISSUE TITLE
Getting this error when trying to export

### ISSUE THREAD

**Issue by swapmasterx** [absolute-quantum/cats-blender-plugin#560]
I have a part named body fwi. 

Python: Traceback (most recent call last):
  File "C:\Users\Izzy\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-0-19-0\tools\importer.py", line 880, in execute
    bpy.ops.cats_importer.display_error('INVOKE_DEFAULT')
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Izzy\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-0-19-0\tools\importer.py", line 966, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 6.1)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float
Location: C:\Program Files (x86)\Steam\steamapps\common\Blender\3.4\scripts\modules\bpy\ops.py:111

**Comment by novajacobsen** [comment]
I had this too, switched to using the [development version](https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip) of the plugin. This was pinned on the FAQ on the discord server. 

I'm a little sad to see no one is going through these issues and talking about this on github if this is something they see frequently on discord, as most people will probably use that as their first line of support
