### ISSUE TITLE
import model error

### ISSUE THREAD

**Issue by Rochiee** [absolute-quantum/cats-blender-plugin#573]
bpy.ops.object.delete(use_global=False, confirm=False)

Deleted 3 object(s)

bpy.context.space_data.system_folders_active = 1

bpy.ops.cats_importer.import_any_model(filepath="D:\\Download\\フィッシュル\\フィッシュル.pmx", files=[{"name":"フィッシュル.pmx", "name":"フィッシュル.pmx"}], directory="D:\\Download\\フィッシュル\\")

bpy.context.space_data.recent_folders_active = 0

bpy.context.space_data.recent_folders_active = 3

Traceback (most recent call last):
  File "C:\Users\ASUS X441UV\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-0-18-0\extern_tools\mmd_tools_local\operators\fileio.py", line 159, in execute
    self.__translator = DictionaryEnum.get_translator(self.dictionary)
  File "C:\Users\ASUS X441UV\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-0-18-0\extern_tools\mmd_tools_local\translations.py", line 323, in get_translator
    return getTranslator(dictionary)
  File "C:\Users\ASUS X441UV\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-0-18-0\extern_tools\mmd_tools_local\translations.py", line 171, in getTranslator
    elif csvfile in bpy.data.texts:
TypeError: bpy_prop_collection.__contains__: expected a string or a tuple of strings

bpy.ops.mmd_tools.import_model(filepath="D:\\Download\\フィッシュル\\フィッシュル.pmx")

**Comment by Rochiee** [comment]
any help pls..
