### ISSUE TITLE
any help?

### ISSUE THREAD

**Issue by Rochiee** [absolute-quantum/cats-blender-plugin#574]
Python: Traceback (most recent call last):
  File "C:\Users\ASUS X441UV\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 969, in execute
    Common.fix_twist_bones(mesh, bones_to_delete)
  File "C:\Users\ASUS X441UV\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-master\tools\common.py", line 2095, in fix_twist_bones
    mix_weights(mesh, vg_twist1.name, vg_twist.name, mix_strength=0.25, delete_old_vg=False)
  File "C:\Users\ASUS X441UV\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-master\tools\common.py", line 1784, in mix_weights
    apply_modifier(mod)
  File "C:\Users\ASUS X441UV\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-master\tools\common.py", line 311, in apply_modifier
    bpy.ops.object.modifier_apply(modifier=mod.name)
  File "D:\blender\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Modifier is disabled, skipping apply

**Comment by Mysteryem** [comment]
You have to use the development version of Cats on Blender 3.0 and newer: https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip (you have to download and install the direct link because changes in Blender 3.1 broke the updater).

This particular issue is caused by a Windows-specific change that occurred in Blender 3.0, which the development version has a fix for.
