### ISSUE TITLE
not being able to export model

### ISSUE THREAD

**Issue by kerry-leanne** [absolute-quantum/cats-blender-plugin#577]
hi im having trouble with cats and trying to export, what it is i wanted to do is i want to export my model and transfer it onto unity but every time i press export i get a message saying:
Python: Trace back (most recent call last):
  File "C:\Users\Hollis\App Data\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 880, in execute
    bpy.ops.cats_importer.display_error('INVOKE_DEFAULT')
  File "C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.4.1.0_x64__ppwjx1n5r4v9t\Blender\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\Hollis\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 966, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 6.1)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float
Location: C:\Program Files\WindowsApps\BlenderFoundation.Blender_3.4.1.0_x64__ppwjx1n5r4v9t\Blender\3.4\scripts\modules\bpy\ops.py:111

is there any way to solve this problem if so please let me know many thanks

**Comment by Yogi891** [comment]
newer versions of blender have this issue with cats however cats uses the following settings for the most part.
just go to file>export>fbx then use the following settings and save them as a preset
or use blender 2.93.10
![image](https://user-images.githubusercontent.com/42818087/220522037-de44605e-e10f-4a62-9e2d-3eafdfa1d35b.png)

**Comment by kerry-leanne** [comment]
Ahh okie dokie I'll give that ago and see what happens I'll update you if it works or not 
Many thanks

**Comment by kerry-leanne** [comment]
hi yogi891 i have some good news and some bad news. the good news is ive installed blender 2.93.10 and cats is working like a charm. the bad news is ive gone into fbx setting to sort all the settings out only to have the same problem like before.
thank you very much for your help much appreciated ^__^

**Comment by uguu-org** [comment]
You could fix this locally yourself by going to the addons directory and find the file and line that's mentioned in the stacktrace, and change where it says `width=dpi_value * 6.1` to `width=int(dpi_value * 6.1)`.

This is what https://github.com/absolute-quantum/cats-blender-plugin/pull/582 does, but I am not sure who can accept it.
