### ISSUE TITLE
Can't Export/Import file (model/map any kind).

### ISSUE THREAD

**Issue by TrueGod221** [absolute-quantum/cats-blender-plugin#589]
Python: Traceback (most recent call last):
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-0-19-0\updater.py", line 85, in execute
    bpy.ops.cats_updater.confirm_update_panel('INVOKE_DEFAULT')
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-0-19-0\updater.py", line 218, in invoke
    return context.window_manager.invoke_props_dialog(self, width=dpi_value * 4.1)
TypeError: WindowManager.invoke_props_dialog(): error with keyword argument "width" -  Function.width expected an int type, not float
Location: C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py:111

Python: Traceback (most recent call last):
  File "C:\Users\Name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-0-19-0\tools\importer.py", line 98, in execute
    for f in self.files:
TypeError: '_PropertyDeferred' object is not iterable

**Comment by 989onan** [comment]
https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip
