### ISSUE TITLE
Error Occurs During Add-On Installation in Blender 3.5

### ISSUE THREAD

**Issue by kazuoay** [absolute-quantum/cats-blender-plugin#591]
Hello to the cats-blender-plugin development team.

I am a user of Blender 3.5 and have encountered an issue with installing add-ons. Whenever I try to install an add-on, an error occurs and it cannot be installed successfully.

Could you please advise if there is a solution to this problem? Thank you very much.

`### Loading CATS...
Skipped 11 CATS updater classes.
mmd_tools is already registered
Skipped 116 CATS classes.
Exception ignored in: <function ImagePreviewCollection.__del__ at 0x00000287A96AB7F0>
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\bpy\utils\previews.py", line 64, in __del__
    raise ResourceWarning(
ResourceWarning: <ImagePreviewCollection id=0x287ac0f13a0[5], <super: <class 'ImagePreviewCollection'>, <ImagePreviewCollection object>>>: left open, remove with 'bpy.utils.previews.remove()'
Exception in module register(): C:\Users\aaaa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-0-19-0\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\aaaa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-0-19-0\__init__.py", line 319, in register
    bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')`

**Comment by idrisz19** [comment]
[The fix is in the development branch](https://github.com/absolute-quantum/cats-blender-plugin/commit/19e3087a8b624719de8005ee9f29e3a68c4caa3e). You can download it from [this link](https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip).

**Comment by SteveGertler** [comment]
thank you... I have a very important job that i need to do with this plugin

**Comment by Reru01** [comment]
This also fixed the issue I was having on blender 1.6.0

**Comment by jtoenjes** [comment]
Thank you!! I'm hoping this add-on will make my animation life SO much easier!
