### ISSUE TITLE
Cannot install Cats plugin.

### ISSUE THREAD

**Issue by Viizipn** [absolute-quantum/cats-blender-plugin#595]
Every time i try to enable CATS it gives me this error:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\candy\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-master\__init__.py", line 319, in register
    bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')

any way on how to fix this? 

Blender vers 3.5.0

**Comment by restlessru** [comment]
I'm having the same issue

**Comment by idrisz19** [comment]
[The fix is in the development branch](https://github.com/absolute-quantum/cats-blender-plugin/commit/19e3087a8b624719de8005ee9f29e3a68c4caa3e). I'm not sure when the developers will merge the patch into the master branch or release a new stable, but for the time being, you can download the fixed version from [this link](https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip).

**Comment by Rose-pride** [comment]
same issue

**Comment by SpaceWolf727** [comment]
Still having the same problem!

Only fix I have found is to go into the referenced file manually and delete the "TESTING" entry. Problem clears up immediately, so anyone still having the issue I encourage to give that a shot. Should show the location for your PC in the error message when you try to enable the plugin

I am quite surprise this bug still exists, honestly. Was it forgotten?
