### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by DrPinkieDie** [absolute-quantum/cats-blender-plugin#597]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\kingc\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-master\__init__.py", line 319, in register
    bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')

**Comment by Dreamer-Zero** [comment]
i keep having this same exact issue

**Comment by idrisz19** [comment]
[The fix is in the development branch](https://github.com/absolute-quantum/cats-blender-plugin/commit/19e3087a8b624719de8005ee9f29e3a68c4caa3e). You can download the fixed version from [this link](https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip).

Frankly, I'm disappointed in the current crop of developers. This issue keeps popping up, yet there hasn't been any updates to the master branch or any new stables. I'm not even a developer for this project, yet this is the third time I had to respond to a bug report on account of the actual developers seemingly not paying attention.

Given the inactivity of the repository owner, I find myself wondering if the current developers even possess the authority to update the master branch or release a new stable. If that's the case, I'm wondering why none of the active developers forked the project in order to develop it at a faster pace.

Failing to keep pace with Blender stable releases isn't acceptable. If the current developers don't clean up their act, they might find themselves competing with a fork.

**Comment by feilen** [comment]
> Given the inactivity of the repository owner, I find myself wondering if the current developers even possess the authority to update the master branch or release a new stable.

:sweat_smile: 

> If that's the case, I'm wondering why none of the active developers forked the project in order to develop it at a faster pace.

https://github.com/feilen/tuxedo-blender-plugin

**Comment by RenAhsAcme** [comment]
> [The fix is in the development branch](https://github.com/absolute-quantum/cats-blender-plugin/commit/19e3087a8b624719de8005ee9f29e3a68c4caa3e). You can download the fixed version from [this link](https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip).
> 
> Frankly, I'm disappointed in the current crop of developers. This issue keeps popping up, yet there hasn't been any updates to the master branch or any new stables. I'm not even a developer for this project, yet this is the third time I had to respond to a bug report on account of the actual developers seemingly not paying attention.
> 
> Given the inactivity of the repository owner, I find myself wondering if the current developers even possess the authority to update the master branch or release a new stable. If that's the case, I'm wondering why none of the active developers forked the project in order to develop it at a faster pace.
> 
> Failing to keep pace with Blender stable releases isn't acceptable. If the current developers don't clean up their act, they might find themselves competing with a fork.

Wow! Thanks! After modifying it according to your method, it works again!
