### ISSUE TITLE
error when trying to enable 

### ISSUE THREAD

**Issue by nuclearHUB** [absolute-quantum/cats-blender-plugin#605]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Nucle\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-master\__init__.py", line 319, in register
    bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')

**Comment by Wulfram-Systems** [comment]
Check the pull requests.. Removing "TESTNG" from
the file has solved the issue.. 


Fixed.
