### ISSUE TITLE
Import Model Error

### ISSUE THREAD

**Issue by SindragosaLedokrylaya** [absolute-quantum/cats-blender-plugin#610]
Error: 
`
Python: Traceback (most recent call last):
  File "C:\Users\Sindragosa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-master\tools\importer.py", line 87, in execute
    Common.remove_unused_objects()
  File "C:\Users\Sindragosa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-master\tools\common.py", line 1519, in remove_unused_objects
    delete_hierarchy(obj)
  File "C:\Users\Sindragosa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-master\tools\common.py", line 1417, in delete_hierarchy
    unselect_all()
  File "C:\Users\Sindragosa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-master\tools\common.py", line 193, in unselect_all
    select(obj, False)
  File "C:\Users\Sindragosa\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-master\tools\common.py", line 217, in select
    obj.select_set(sel)
AttributeError: 'NoneType' object has no attribute 'select_set'
`
OS: Windows 10
Blender: 3.5.1
Cats-blender-plugin: master (+ manualy delete 'TESTING' in __init__.py)

**Comment by ARANARA222** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\Natusya\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cats-blender-plugin-patch-2\tools\importer.py", line 115, in execute
    context.scene.zip_content = zip_path + ' ||| ' + files[0]
TypeError: bpy_struct: item.attr = val: enum "E:\Загрузки\Barbara_1602301315_6698.zip ||| Ñ╨⌐`Ñ╨ÑΘ/Ñ╨⌐`Ñ╨ÑΘ.pmx" not found in ()

**Comment by Mysteryem** [comment]
Turns out this was caused by a Blender bug introduced in Blender 3.4.0: https://projects.blender.org/blender/blender/issues/113378
