### ISSUE TITLE
cannot activate plugin

### ISSUE THREAD

**Issue by balevato** [absolute-quantum/cats-blender-plugin#613]
blender 3.5

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\balev\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\cats-blender-plugin-master\__init__.py", line 319, in register
    bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')

**Comment by CollieMasked** [comment]
https://github.com/absolute-quantum/cats-blender-plugin/issues/595#issuecomment-1493425995

they havent uploaded a stable ver yet but i recommend looking at this comment to help :)
