### ISSUE TITLE
google translate : Failed to connect. Probable cause: timeout

### ISSUE THREAD

**Issue by charles0122** [absolute-quantum/cats-blender-plugin#619]
Python: Traceback (most recent call last):
  File "F:\Blender\3.0\python\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "F:\Blender\3.0\python\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "F:\Blender\3.0\python\lib\site-packages\urllib3\connection.py", line 364, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "F:\Blender\3.0\python\lib\site-packages\urllib3\connection.py", line 501, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "F:\Blender\3.0\python\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "F:\Blender\3.0\python\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "F:\Blender\3.0\python\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "F:\Blender\3.0\python\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "F:\Blender\3.0\python\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Blender\3.0\python\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "F:\Blender\3.0\python\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "F:\Blender\3.0\python\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /_/TranslateWebserverUi/data/batchexecute (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Arce\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\extern_tools\google_trans_new\google_trans_new.py", line 145, in translate
    r = s.send(request=response.prepare(),
  File "F:\Blender\3.0\python\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "F:\Blender\3.0\python\lib\site-packages\requests\adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='translate.google.com', port=443): Max retries exceeded with url: /_/TranslateWebserverUi/data/batchexecute (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Arce\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 445, in execute
    # Combines same materials
  File "C:\Users\Arce\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\translate.py", line 438, in update_dictionary
    print('NO PERMISSION TO USE GOOGLE TRANSLATE!')
  File "C:\Users\Arce\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\tools\translate.py", line 438, in <listcomp>
    print('NO PERMISSION TO USE GOOGLE TRANSLATE!')
  File "C:\Users\Arce\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\cats-blender-plugin-master\extern_tools\google_trans_new\google_trans_new.py", line 208, in translate
    r.raise_for_status()
cats-blender-plugin-master.extern_tools.google_trans_new.google_trans_new.google_new_transError: Failed to connect. Probable cause: timeout

location: <unknown location>:-1

**Comment by charles0122** [comment]
**version details**
blender  3.0.1  
cats-blender-plugin 0.19.0

**Comment by charles0122** [comment]
change  cats-blender-plugin version to 0.19.1-devlopment  and uncheck "join meshes" item in "fix model" button can success ! 
but i don't open export fbx model by previous step  and inport unity will lose materials
