### ISSUE TITLE
can't open cat

### ISSUE THREAD

**Issue by nethack37** [absolute-quantum/cats-blender-plugin#629]
Traceback (most recent call last):
  File "E:\app\blender\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\nethack\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cats-blender-plugin-0-19-0\__init__.py", line 319, in register
    bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')

**Comment by windskyxb** [comment]
same peoblem on steam version by 3.6.1 LTS
![image](https://github.com/absolute-quantum/cats-blender-plugin/assets/60282327/f450b804-6c8f-43a5-8a12-022cee6fa857)
![image](https://github.com/absolute-quantum/cats-blender-plugin/assets/60282327/580325be-d2a3-4112-9620-2baf427a735e)

**Comment by Owenm05** [comment]
same here

**Comment by mjwallcodes** [comment]
same here also

**Comment by N1ades** [comment]
Try using v3.3 LTS

**Comment by windskyxb** [comment]
> Try using v3.3 LTS

Yes, v3.3 LTS can be used normally
![image](https://github.com/absolute-quantum/cats-blender-plugin/assets/60282327/318e263b-41fd-4652-a64f-48d7072c7905)
![image](https://github.com/absolute-quantum/cats-blender-plugin/assets/60282327/29670f4c-d8eb-4517-a58a-61f1ee9b7c42)

**Comment by Cyanflower** [comment]
I found the problem , Open this directory , If you using version is 3.6 , You can copy and paste it into the address bar and press Enter to jump ,
有一个手动修复的方法，打开插件目录，3.6版本的直接复制下面的地址到文件管理器地址栏按回车跳转
![R{`BU`UC}7$E$I LAS_(6E3](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/45cafbfc-f221-4105-828c-eb427a15e0c5)
%USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cats-blender-plugin-0-19-0
Open the folder inside  __init__.py 
打开里面的__init__.py
![20230731034913](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/dc818355-b258-4d70-b9ef-263d32dfae40)
Go to line 319 ,
跳到319行
![20230731033632](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/be597a06-4b49-4ce7-823f-0f4204c3695d)
modification {'OFFICIAL', 'COMMUNITY', 'TESTING'} to {'OFFICIAL', 'COMMUNITY'}
把 {'OFFICIAL', 'COMMUNITY', 'TESTING'} 改成 {'OFFICIAL', 'COMMUNITY'} 
![20230731033643](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/3961f35a-56a7-4e6c-b9a0-7cd4a8059ef3)
and save,
然后保存
The reason seems to be a ui change in version 3.6, which changed the original three categories of 'OFFICIAL' 'COMMUNITY' 'TESTING' to 'OFFICIAL' 'COMMUNITY'.
原因差不多就是新版本把以前ui界面的"官方" "社区" "测试"改成了"官方" "社区" 
![289JO17`M@TVE4}VV%@ M@O](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/99b15dd0-84b8-4360-85a9-f002c9b64cb1)

**Comment by Xeon-acid** [comment]
> I found the problem , Open this directory , If you using version is 3.6 , You can copy and paste it into the address bar and press Enter to jump , 有一个手动修复的方法，打开插件目录，3.6版本的直接复制下面的地址到文件管理器地址栏按回车跳转 ![R{`BU`UC}7$E$I LAS_(6E3](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/45cafbfc-f221-4105-828c-eb427a15e0c5) %USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\cats-blender-plugin-0-19-0 Open the folder inside **init**.py 打开里面的__init__.py ![20230731034913](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/dc818355-b258-4d70-b9ef-263d32dfae40) Go to line 319 , 跳到319行 ![20230731033632](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/be597a06-4b49-4ce7-823f-0f4204c3695d) modification {'OFFICIAL', 'COMMUNITY', 'TESTING'} to {'OFFICIAL', 'COMMUNITY'} 把 {'OFFICIAL', 'COMMUNITY', 'TESTING'} 改成 {'OFFICIAL', 'COMMUNITY'} ![20230731033643](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/3961f35a-56a7-4e6c-b9a0-7cd4a8059ef3) and save, 然后保存 The reason seems to be a ui change in version 3.6, which changed the original three categories of 'OFFICIAL' 'COMMUNITY' 'TESTING' to 'OFFICIAL' 'COMMUNITY'. 原因差不多就是新版本把以前ui界面的"官方" "社区" "测试"改成了"官方" "社区" ![289JO17`M@TVE4}VV%@ M@O](https://github.com/absolute-quantum/cats-blender-plugin/assets/126191477/99b15dd0-84b8-4360-85a9-f002c9b64cb1)

Pretty thanks! I got same error in blender 4.3, and fixed it with your steps.
