### ISSUE TITLE
Python error when trying to enable plugin

### ISSUE THREAD

**Issue by KeikoPima** [absolute-quantum/cats-blender-plugin#654]
When enabling the plugin this error comes back but iti seems like it does get enabled but none of the buttons or features work

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\addon_utils.py", line 401, in enable
    mod.register()
  File "C:\Users\puree\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\cats-blender-plugin-0-19-0\__init__.py", line 319, in register
    bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
ValueError: bpy_struct: item.attr = val:: 'TESTING' not found in ('OFFICIAL', 'COMMUNITY')

**Comment by uraquitanfilho** [comment]
same issue

**Comment by RinaDev-xyz** [comment]
Make sure you use the dev version of cats:

https://github.com/absolute-quantum/cats-blender-plugin/tree/development
Direct link to zip file: https://github.com/absolute-quantum/cats-blender-plugin/archive/refs/heads/development.zip

The current released versions will not work blender 3.6. 

Also Blender 4.0 is also not supported by cats due to the fact cats has no been updated plus MMD tools which cats uses is outdated. I would either find a unofficial version (I working on one myself) which supports blender 4.0 or downgrade to blender 3.6.

**Comment by yanlanfeixue** [comment]
Try replacing
 `bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}` 
with
 `bpy.context.window_manager.addon_support = {'OFFICIAL', 'COMMUNITY',}`

**Comment by RinaDev-xyz** [comment]
Yes that will fix this error however as stated the main branch shouldn't really be used on newer versions of blender for many reasons. (Dev version contains fixes and compatibility changes the main branch doesn't have from what I am aware of).

But especially shouldn't be using blender 4.0 as the above fix will only put a very small bandage on a larger wound and you will run into A LOT of issues especially when using the main branch on 4.0.

**Comment by yanlanfeixue** [comment]
I found this problem recently, and more faults have not been checked yet. I wonder if there is a branch that has been fixed that can be used?

**Comment by RinaDev-xyz** [comment]
There are unofficial versions of cats which does fix issues for 3.6 and 4.0. however there is no official source and I doubt there will be as at this point cats has been abandoned by the original developer. It was community supported on the dev branch but it also seems that this support has more or less ended due to issues with the owner of the repo.

However for blender 4.0 there are un official (including my own) ones that fix cats issues however mmd tools is still not updated fully for blender 4.0 so even if you fix cats side of things for 4.0 we still have to wait for mmd tools to be fully updated and compatible for all issues to be resolved. However with fixes cats does seem to work mostly on 4.0 (there are some things that break due to mmd tools tho).

**Comment by yanlanfeixue** [comment]
tks! next I will try MMD Tools to solve this problem. 
Thanks again for your reply!

**Comment by RinaDev-xyz** [comment]
The OP issue is not a MMD tools issue and is a cats issue just fyi.

However mmd tools for 4.0 is being worked on, it's just slow atm. If you are having an issue please post it on cats first before going to MMD tools so it can be confirmed if it's a MMD tools or a cats issue, unless you know for certain it's a mmd tools issue.

If you are using 4.0 there are fixes of cats in pull request #648 which you can apply yourself which does fix most 4.0 issues on cats side, however make sure you use the dev version of cats if you do.

**Comment by wh1le** [comment]
Same issue, I downgraded to blender 3.6 and it still persists

**Comment by RinaDev-xyz** [comment]
Maybe your should read [this](https://github.com/absolute-quantum/cats-blender-plugin/issues/670), no point reporting issues as this cats is basically abandoned.
