### ISSUE TITLE
issue whe3n fixing modle

### ISSUE THREAD

**Issue by k9streaming** [absolute-quantum/cats-blender-plugin#658]
i am having problem to where when i import  my model  the bones and model dont line up so i use fix model and i get an erorr with line 1195 file armature.py and line1846 file common.py how can i fix this

**Comment by k9streaming** [comment]
Traceback (most recent call last):
  File "C:\Users\chatt\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 1195, in execute
    Common.fix_bone_orientations(armature)
  File "C:\Users\chatt\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cats-blender-plugin-master\tools\common.py", line 1846, in fix_bone_orientations
    if len(bone.parent.children) == 1:  # if the bone's parent bone only has one child, connect the bones (Don't connect them all because that would mess up hand/finger bones)
AttributeError: 'NoneType' object has no attribute 'children'

location: <unknown location>:-1
is what i get

**Comment by RinaDev-xyz** [comment]
Your better going on the discord for help as this isn't monitored by anyone really.
